// Generated by ts-to-zod
import { z } from "zod";

export const addonCategorySchema = z.object({});

export const addonPriceTypeSchema = z.object({});

export const addonUpdateSchema = z.object({
    name: z.union([z.string(), z.any()]).optional().nullable(),
    category: z.union([addonCategorySchema, z.any()]).optional().nullable(),
    price_type: z.union([addonPriceTypeSchema, z.any()]).optional().nullable(),
    price: z.union([z.number(), z.string(), z.any()]).optional().nullable(),
    is_active: z.union([z.boolean(), z.any()]).optional().nullable()
});

export const adminDeviceCreateSchema = z.object({
    name: z.string(),
    is_active: z.boolean().optional()
});

export const adminRecoveryRequestSchema = z.object({
    email: z.string(),
    password: z.string(),
    otp_code: z.union([z.string(), z.any()]).optional().nullable(),
    recovery_code: z.union([z.string(), z.any()]).optional().nullable()
});

export const glassTypeCreateSchema = z.object({
    name: z.string(),
    price_per_sqm: z.union([z.number(), z.string()]).nullable()
});

export const glassTypeUpdateSchema = z.object({
    name: z.union([z.string(), z.any()]).optional().nullable(),
    price_per_sqm: z.union([z.number(), z.string(), z.any()]).optional().nullable()
});

export const inventoryAdjustRequestSchema = z.object({
    adjustment: z.number(),
    reason: z.union([z.string(), z.any()]).optional().nullable()
});

export const inventoryItemCreateSchema = z.object({
    item_type: z.enum(["glass", "hardware", "others"], { required_error: "Material type is required" }),
    material_name: z.string().min(1, "Item name is required"),
    description: z.string().optional().nullable(),
    size: z.string().optional().nullable(),
    thickness: z.string().optional().nullable(),
    unit: z.string().optional().nullable(),
    price: z.union([z.number(), z.string()]).optional().nullable(),
    stock_count: z.number().optional(),
    low_stock_threshold: z.number().optional(),
});

export const inventoryItemUpdateSchema = z.object({
    material_name: z.union([z.string(), z.any()]).optional().nullable(),
    size: z.union([z.string(), z.any()]).optional().nullable(),
    thickness: z.union([z.string(), z.any()]).optional().nullable(),
    unit: z.union([z.string(), z.any()]).optional().nullable(),
    stock_count: z.union([z.number(), z.any()]).optional().nullable(),
    low_stock_threshold: z.union([z.number(), z.any()]).optional().nullable()
});

export const orderCreateSchema = z.object({
    customer_name: z.string(),
    customer_email: z.string(),
    customer_phone: z.string(),
    width: z.union([z.number(), z.string()]).nullable(),
    height: z.union([z.number(), z.string()]).nullable(),
    sheet_size: z.union([z.string(), z.any()]).optional().nullable(),
    thickness: z.union([z.string(), z.any()]).optional().nullable(),
    drill_holes_count: z.union([z.number(), z.any()]).optional().nullable(),
    hole_diameter: z.union([z.number(), z.string(), z.any()]).optional().nullable(),
    tint_type: z.union([z.string(), z.any()]).optional().nullable(),
    engraving_text: z.union([z.string(), z.any()]).optional().nullable(),
    glass_type_id: z.string(),
    addon_ids: z.array(z.string()).optional(),
    insurance_selected: z.boolean().optional()
});

export const orderStatusUpdateSchema = z.object({
    order_status: z.string()
});

export const orderUpdateSchema = z.object({
    customer_name: z.union([z.string(), z.any()]).optional().nullable(),
    customer_email: z.union([z.string(), z.any()]).optional().nullable(),
    customer_phone: z.union([z.string(), z.any()]).optional().nullable(),
    width: z.union([z.number(), z.string(), z.any()]).optional().nullable(),
    height: z.union([z.number(), z.string(), z.any()]).optional().nullable(),
    sheet_size: z.union([z.string(), z.any()]).optional().nullable(),
    thickness: z.union([z.string(), z.any()]).optional().nullable(),
    drill_holes_count: z.union([z.number(), z.any()]).optional().nullable(),
    hole_diameter: z.union([z.number(), z.string(), z.any()]).optional().nullable(),
    tint_type: z.union([z.string(), z.any()]).optional().nullable(),
    engraving_text: z.union([z.string(), z.any()]).optional().nullable(),
    glass_type_id: z.union([z.string(), z.any()]).optional().nullable(),
    addon_ids: z.union([z.array(z.string()), z.any()]).optional().nullable(),
    order_status: z.union([z.string(), z.any()]).optional().nullable(),
    insurance_selected: z.union([z.boolean(), z.any()]).optional().nullable()
});

export const paymentInitializeSchema = z.object({
    order_id: z.string()
});

export const paystackCallbackSchema = z.object({
    reference: z.string()
});

export const pricingSettingsUpdateSchema = z.object({
    tax_rate: z.union([z.number(), z.string(), z.any()]).optional().nullable(),
    insurance_rate: z.union([z.number(), z.string(), z.any()]).optional().nullable()
});

export const recoveryCodeItemSchema = z.object({
    code_hint: z.string(),
    used_at: z.union([z.string(), z.any()]).optional().nullable()
});

export const staffDeviceCreateSchema = z.object({
    name: z.string(),
    email: z.union([z.string(), z.any()]).optional().nullable(),
    is_active: z.boolean().optional()
});

export const totpConfirmRequestSchema = z.object({
    otp_code: z.string()
});

export const userCreateSchema = z.object({
    name: z.string(),
    email: z.string(),
    password: z.string()
});

export const addonCreateSchema = z.object({
    name: z.string(),
    category: z.union([addonCategorySchema, z.any()]).optional().nullable(),
    price_type: addonPriceTypeSchema,
    price: z.union([z.number(), z.string()]).nullable(),
    is_active: z.boolean().optional()
});
